name: Generate JSON from Environment Variables
on:
  push:
    branches:
      - main

jobs:
  generate_json:
    runs-on: ubuntu-latest
    env:
      IVT_PUMKIN134_CENTRAL_DEFAULT_ELASTICACHE: '{"cluster_mode": "false"}'
      IVT_PUMKIN134_PIE_DEFAULT_ELASTICACHE: '{"cluster_mode": "false"}'
      IVT_PUMKIN134_CLOUDAUTH_DEFAULT_ELASTICACHE: '{"cluster_mode": "false"}'
      TEST_ENV: 'test_env'
      TEST_ENV1: 'test_env'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: execute python script
        run: |
          python additonal_infra.py
          echo $ADDITONAL_INFRA
